db:
  # Esta linea descarga el contenedor desde un registro en la red
  # image: <IP-REGISTRO>:5000/jcs-demo:db-prueba-1
  # Esta linea descarga el contenedor desde un registro en la nube
  image: crulises/jcs-demo:db-prueba-1
  container_name: jcs-db
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: prueba
  ports:
    - "3306:3306"
